language: python

branches:
  only:
  - master
  - testing
  - tooling
  - refactor

matrix:
  include:
    - python: 3.6
      env:  TRAVIS_NODE_VERSION=10

cache:
  directories:
    - lektor/admin/node_modules

install:
  - travis_retry pip install --upgrade pytest
  - travis_retry pip install --editable .[test]

before_script:
  - python --version
  - pip list

script: pytest tests

notifications:
  email: false
